export const skillsList = [
    '5g', 'adobe', 'ai ml marketplace products', 'ai programming',
    'angular', 'ansible', 'api development', 'api management services',
    'ai algorithms', 'ai ml', 'apis', 'application maps', 'application software',
    'argocd', 'asp.net mvc', 'authentication', 'autocad', 'autonomous navigation and localization',
    'aws', 'aws material properties', 'azure', 'azure apim', 'b2x apps', 'ballast water inspection',
    'banking', 'bgp configuration', 'big data', 'bitrise', 'blockchain architecture', 'bolting',
    'building codes', 'c programming', 'c#', 'c++', 'capacity building', 'ci-cd', 'ci/cd', 'circuit design',
    'cisco routing', 'clinical trial', 'cloud', 'cloud computing', 'cloud messaging', 'cloud networking',
    'communication protocols', 'comos', 'competitor analysis', 'computer vision', 'connected applications',
    'connected devices', 'consensus algorithms', 'construction', 'construction management', 'construction manager',
    'construction methods', 'context api', 'control system design', 'control systems', 'cross-border payment providers',
    'cryptography', 'css', 'customer journeys', 'dapps', 'data analysis', 'data analytics', 'data encryption',
    'data engineering', 'data mining', 'data science', 'data scientist', 'data visualization', 'debugging tools',
    'deep learning', 'device management', 'devops', 'distributed ledger', 'distributed systems', 'docker',
    'documentation and reporting', 'dr', 'drug safety', 'ecosystem maps', 'edge compute platforms', 'electrical',
    'electrical design', 'electrical engineering', 'electrical safety standards', 'embedded c', 'embedded linux',
    'embedded software', 'embedded systems', 'enterprise networks', 'environmental assessment',
    'environmental due diligence', 'environmental impact assessments', 'environmental risk management',
    'eplan', 'esf requirements', 'etap electrical transient analyzer program', 'exchange houses', 'execution',
    'fabrication processes', 'fastlane', 'feature engineering', 'figma', 'finite element packages',
    'fintech', 'firebase', 'firestore', 'firewall management', 'firewalls management', 'firmware development',
    'fixed networks', 'flac 2d/3d', 'foundation design', 'game design', 'gazebo', 'gcp',
    'gcp devops engineer', 'gcp platform', 'gen ai', 'gen ai engineer', 'generative ai models', 'generators',
    'geo5', 'geophysical surveys', 'geotechnical data interpretation', 'geotechnical engineering', 'geotechnical surveys',
    'git', 'github actions', 'google apigee', 'grafana', 'graphql  javascript', 'hana', 'hardware debugging',
    'hardware engineer', 'high availability', 'html', 'html5', 'human-robot interaction', 'hyperledger', 'incident response',
    'infrastructure project', 'interaction', 'internship', 'iot and device engineering', 'iot protocols', 'ipfs',
    'java', 'javascript', 'java script', 'javascripts', 'keras', 'kotlin', 'kubernetes', 'lan/wan design', 'land',
    'langchain', 'linux', 'llm', 'load balancing', 'malware analysis', 'mbs metal building software',
    'mechanical and hardware integration', 'microcontrollers', 'microsoft excel', 'miro', 'ml', 'ml algorithm',
    'mlflow', 'mobx', 'model deployment', 'monitoring', 'my sql', 'natural habitats conservation', 'network engineer',
    'network monitoring', 'network programming', 'network security', 'networking', 'nlp', 'node.js', 'objective-c redux',
    'occupational health and safety', 'oci', 'offshore', 'opensearch', 'oracle fusion', 'pandas', 'path planning',
    'pcb layout', 'pcs7 system', 'penetration testing', 'performance optimization', 'pharmacovigilance', 'physics simulation',
    'pipe-soil interaction analysis', 'pipeline', 'plaxis 2d/3d', 'plumbing', 'power bi', 'power distribution systems',
    'power system analysis', 'power systems', 'product management', 'product strategy', 'project management',
    'projects', 'protection coordination diagrams', 'protective relays', 'prototyping', 'python', 'python programming',
    'react native', 'real estate', 'redhat openshift container', 'redux', 'reinforced concrete', 'remittances', 'rest apis',
    'restful apis', 'risk management', 'robot operating system', 'robotic system design and development',
    'robotics programming and control', 'robotics simulation and testing', 'robotics system integration', 'ros',
    'rtos', 'safety regulations', 'sales', 'sap abap', 'satellite networks', 'scada integration', 'scikit-learn', 'scm',
    'scripting', 'security auditing', 'senior cloud engineer', 'senior ui/ux designer', 'sensing and perception',
    'sensor integration', 'service blueprints', 'settle3', 'shader development', 'siem tools', 'signal processing',
    'simulation software', 'simulation tools', 'single-line diagrams', 'site inspection', 'sketch', 'smart contracts',
    'software engineers', 'solidity', 'sppa-t3000', 'springboot', 'sql', 'staad pro', 'statistical analysis', 'statistics',
    'steel design', 'structural analysis', 'structural design', 'structural engineering', 'surveying techniques', 'swift',
    'switchgear', 'sysdig', 'tcp/ip protocols', 'technical training', 'techno-functional support', 'tekla',
    'telco cloud automation', 'tensorflow', 'terraform', 'threat analysis', 'transformers', 'trend benchmarking',
    'troubleshooting skills', 'typescript', 'ui/ux design', 'unity', 'unreal engine', 'ups', 'user flow diagrams',
    'user research', 'v-rep', 'vba', 'vector stores', 'version control', 'visual basic macros', 'voip technologies',
    'vpn configuration', 'vulnerability assessment', 'wan optimization', 'water', 'wbg safeguard policies', 'web3.js',
    'webots', 'welding', 'wfm', 'wireframing', 'wireless communication', 'wireless technologies', 'xdisp', 'xml'
]
